module.exports = {
  baseUrl: "https://www.saucedemo.com/",
  landingPageUrl: "https://www.saucedemo.com/inventory.html",
  title: "Swag Labs",
  sauceLabsTitle: "Sauce Labs: Cross Browser Testing, Selenium Testing & Mobile Testing",
  sauceLabsUrl: "https://saucelabs.com/",
  onesie: "$7.99",
  fleeceJacket: "$49.99",
  tShirtRed: "$15.99",
  backPack: "$29.99",
  twitterTitle: "Twitter",
  twitterUrl: "https://x.com/saucelabs",
  facebookTitle: "Sauce Labs | Facebook",
  facebookUrl: "https://www.facebook.com/saucelabs",
  linkedInTitle: "LinkedIn",
  linkedInUrl: "https://www.linkedin.com",
  yourCartUrl: "https://www.saucedemo.com/cart.html",
  checkoutYourInformationUrl: "https://www.saucedemo.com/checkout-step-one.html",
  checkoutOverviewUrl: "https://www.saucedemo.com/checkout-step-two.html",
  checkoutCompleteUrl: "https://www.saucedemo.com/checkout-complete.html",
  productDetailsPageUrl: "https://www.saucedemo.com/inventory-item.html?id=4",
};